version: '3.4'

services:
  postgresql.data:
    image: postgres

  testapp:
    image: testapp
    build:
      context: .
      dockerfile: Test_App/Dockerfile
    depends_on:
      - postgresql.data