apiVersion: v1
kind: ConfigMap
metadata:
  name: externalcfg
  namespace: test-app
  labels:
    app: test-app
data:
  SqlDb: Host=postgresql-data;Port=5432;Database=tr-currencies;Username=test-user;Password=postgres1
---
apiVersion: v1
kind: Service
metadata:
  name: test-application
  namespace: test-app
  labels:
    app: test-app
    component: app
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: test-app
    component: app
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-application
  namespace: test-app
spec:
  template:
    metadata:
      labels:
        app: test-app
        component: app
    spec:
      containers:
      - name: testapp
        image: localhost:5000/testapp
        env:
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
           configMapKeyRef:
             name: externalcfg
             key: SqlDb  
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-data
  namespace: test-app
  labels:
    app: test-app
    component: postgres
spec:
  type: NodePort
  ports:
  - port: 5432
  selector:
    app: test-app
    component: postgres
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgresql-data
  namespace: test-app
spec:
  template:
    metadata:
      labels:
        app: test-app
        component: postgres
    spec:
      containers:
      - name: postgresql-data
        image: postgres
        env:
        - name: POSTGRES_PASSWORD
          value: postgres1
        - name: POSTGRES_USER
          value: test-user  
---